### PR TITLE
Fix TargetTemp update on homebridge when updating on haas web interface

### PR DESCRIPTION
**Pull request by Minims**
@robbiet480 New pull request for improvements/fix we can add in the next days.

This first commit is to report in homebridge any update of TargetTemp made in hass web interface.

### CODE REVIEW

**Comment by robbiet480** [comment]
Ready to merge?

**Comment by Minims** [comment]
Yes.

**Comment by Minims** [comment]
@robbiet480 I've ask you here because I'm sure I have to open an issue et make a pull request. I've a problem with cover/rullershutter on binary mode.

the current code always send close to hass even if I open or close the cover :/ 


my fix : 

```
+++ accessories/cover.js        2017-03-21 21:19:28.259564403 +0100
@@ -148,8 +148,10 @@
     if (!(position === 100 || position === 0)) {
       this.log('Cannot set this cover to positions other than 0 or 100');
       callback(communicationError); // TODO
+    } else if ( position === 100){
+      this.doChangeState('open_cover', callback);
     } else {
-      this.doChangeState(position === '100' ? 'open_cover' : 'close_cover', callback);
+      this.doChangeState('close_cover', callback);
     }
```

don't  know if it's the normal behaviour.

**Comment by robbiet480** [comment]
Cover is never something i've worked on since I don't have any. Feel free to submit a PR to fix it if you think it's broken.

**Pull request merged**
