### PR TITLE
Lock & Garage Door Device Support

### PR DESCRIPTION
**Pull request by devdelay**
Add support for lock and garage_door devices.

### CODE REVIEW

**Comment by philk** [comment]
I don't have a garage door to test but the lock works great for me, thanks!

**Comment by maddox** [comment]
Sorry I totally flaked on this repo this summer. Catching up now. Thanks for the contribution!

**Comment by maddox** [comment]
Could you resolve the conflicts? I'll merge this right away.

**Comment by robbiet480** [comment]
Took care of it myself, 'twas just a minor conflict in README.md.

**Comment by maddox** [comment]
hawt

**Pull request merged**
