### PR TITLE
Add a brightness characteristics only when needed

### PR DESCRIPTION
**Pull request by shmuelzon**

### CODE REVIEW

**Comment by 2ndalpha** [comment]
Please merge this PR

**Comment by robbiet480** [comment]
I just realized that with this PR merged lights which support brightness will only do so as long as brightness is above 0 when Homebridge starts up, since Home Assistant hides the brightness attribute if it is equal to 0...

**Comment by maddox** [comment]
ewwwwwwww yeah. I always wondered what the motivation behind that was in Home Assistant. Should that change on the HA side? I feel like this exact scenario exposes it as sort of wrong.

**Comment by robbiet480** [comment]
@shmuelzon @2ndalpha @maddox Thoughts on rolling this back for now?

**Comment by maddox** [comment]
👍

**Comment by shmuelzon** [comment]
I would rather fix the root cause, though I'm not sure what the best approach here. It seems that if a light is turned off, no attributes (including brightness) are exposed. Would it be correct to simply always export them?
```patch
diff --git a/homeassistant/components/light/__init__.py b/homeassistant/components/light/__init__.py
index 2a87d2e..430cb33 100644
--- a/homeassistant/components/light/__init__.py
+++ b/homeassistant/components/light/__init__.py
@@ -276,16 +276,15 @@ class Light(ToggleEntity):
         """Return optional state attributes."""
         data = {}
 
-        if self.is_on:
-            for prop, attr in PROP_TO_ATTR.items():
-                value = getattr(self, prop)
-                if value:
-                    data[attr] = value
-
-            if ATTR_RGB_COLOR not in data and ATTR_XY_COLOR in data and \
-               ATTR_BRIGHTNESS in data:
-                data[ATTR_RGB_COLOR] = color_util.color_xy_brightness_to_RGB(
-                    data[ATTR_XY_COLOR][0], data[ATTR_XY_COLOR][1],
-                    data[ATTR_BRIGHTNESS])
+        for prop, attr in PROP_TO_ATTR.items():
+            value = getattr(self, prop)
+            if value:
+                data[attr] = value
+
+        if ATTR_RGB_COLOR not in data and ATTR_XY_COLOR in data and \
+           ATTR_BRIGHTNESS in data:
+            data[ATTR_RGB_COLOR] = color_util.color_xy_brightness_to_RGB(
+                data[ATTR_XY_COLOR][0], data[ATTR_XY_COLOR][1],
+                data[ATTR_BRIGHTNESS])
 
         return data
```
It seems to leave the UI in a somewhat inconsistent state. For example, turning the brightness to 0 will effectively turn the light off (changing its state to 'off' but leaving the brightness attribute as was before). The UI will show the light as off, brightness as zero (though the JSON keeps the original value) and the color temperature remains unchanged. Refreshing the UI and clicking on the light will show the brightness as 0 and the temperature as 0 as well now.
Maybe the above patch is OK but the UI will need to hide the additional attributes if the state is 'off'.

@balloob, thoughts?

**Comment by balloob** [comment]
This topic comes up from time to time. The current behavior is what we
want. A light that's off has no brightness or color, so neither should be
exposed.

**Comment by shmuelzon** [comment]
OK, new plan: create a capabilities/supported features similar to the media player component.
Except, I would rather it be a string array rather that bitfield since bitfields in JSON/REST APIs (without any way to get each bit's meaning) make me feel all dirty inside.

**Comment by balloob** [comment]
Each state is always sent over completely. String arrays will increase the
size significantly which will impact data usage when loading the app,
streaming changes and the database

**Comment by maddox** [comment]
Why isn't the brightness sent over as 0 or nil when it has no brightness. To me, the lack of a key in json means that that property just does not exist. 

For me, a light without brightness would never have a brightness key, and a light that supports brightness would always have a brightness key, using either 0 or nil for its value when turned off.

**Comment by maddox** [comment]
>Each state is always sent over completely.

Except for this brightness key which is either there or not there, based on state, not based on capability. 

I think the capabilities key for lights is a great idea. Yeah, it grows the json, but we're talking about a single bitmask here, that's not too much. It also follows an existing pattern. And I'd wager that lights are probably the most important component in HA, why not give it a little more support. Especially since a light CAN support so many different things: brightness, color, saturation, temperature. Lots of different types of bulbs out there.

**Comment by maddox** [comment]
Fwiw, I did revert this and pushed up `1.4.0` since this was essentially broken.

**Comment by balloob** [comment]
Sorry, let me clarify. I'm not against sending over capabilities. I don't
like the idea of a string array.

**Comment by shmuelzon** [comment]
Looks like I'm on my own with regards to the string array vs. bitfield. Though I don't think every field needs to be streamed and surely not all attributes should be saved to the DB but that's a different matter.

I will see what it takes to add a capabilities field to the light component and create a pull request for it when ready. Then we can revisit this issue and fix it properly.

**Comment by balloob** [comment]
If we don't stream or save everything we have to start adding knowledge of
what we are streaming and saving thus coupling the components

**Pull request merged**
