### PR TITLE
Add setTimeout to setBrightness

### PR DESCRIPTION
**Pull request by olekenneth**
This is to make sure it finishes last. Now it's setting my lights to 100% then to dim level or it sets to dim level then 100%.

### CODE REVIEW

**Comment by robbiet480** [comment]
I understand the need for this but don't like it at all. The fix should really be have the `Characteristic.On` use `setPowerState` if the light _does not_ support brightness and use `setBrightness` if it does support brightness since `setBrightness` turns the device on _and_ sets the brightness.

**Comment by olekenneth** [comment]
Yes, that would be a better idea. But from what I read is that controlled by Apple. So I don't see that would be changed anytime soon.

**Comment by tobre6** [comment]
Explain it to me please, why this is necessary? I have working with lights component and haven't seen the need of that.

**Comment by olekenneth** [comment]
When I try to set set new brightness via HomeKit:

`
[HomeAssistant] Setting brightness on the 'Speillys' to 49
[1/29/2017, 12:13:53 AM] [HomeAssistant] Setting power state on the 'Speillys' to on
[1/29/2017, 12:13:53 AM] [HomeAssistant] Successfully set brightness on the 'Speillys' to 49
[1/29/2017, 12:13:53 AM] [HomeAssistant] Successfully set power state on the 'Speillys' to on
`

**Comment by robbiet480** [comment]
I misunderstood the situation when I wrote that comment and have now realized that this is correct.

More info available at https://github.com/nfarina/homebridge/issues/807

@olekenneth Can you increase from 100ms to 800ms as per the linked issue? Once you do that I can accept!

**Comment by olekenneth** [comment]
@robbiet480 Done!

**Comment by olekenneth** [comment]
Merge?

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Comment by rbhr** [comment]
Hey guys I think it is since this update that I receive the following:

/usr/lib/node_modules/homebridge-homeassistant/accessories/light.js:202
            this.log('Setting brightness on the \''+this.name+'\' to ' + level);
                 ^

TypeError: this.log is not a function
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-homeassistant/accessories/light.js:202:18)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by diplix** [comment]
i can confirm this bug. if i remove the timeout function, everything is back to normal  again.

**Comment by shmuelzon** [comment]
Probably missing this (pun intended):
```patch
diff --git a/accessories/light.js b/accessories/light.js
index 5dc2d0d..42db595 100644
--- a/accessories/light.js
+++ b/accessories/light.js
@@ -145,7 +145,7 @@ HomeAssistantLight.prototype = {
                     callback(communicationError);
                 }
             }.bind(this));
-        }, 800);
+        }.bind(this), 800);
     },
     getServices: function() {
         this.lightbulbService = new Service.Lightbulb();
```

**Comment by robbiet480** [comment]
@shmuelzon Good catch!

**Comment by robbiet480** [comment]
Fix deployed to npm as version `2.0.3`.

**Comment by rbhr** [comment]
Many thanks @shmuelzon @robbiet480 works a charm. Current 2.0.3 is an all round winner.

**Comment by boojew** [comment]
I am still experiencing this issue on 2.3.1 using ios11.. anyone else?

**Comment by timokli** [comment]
me too :(

**Pull request merged**
