### PR TITLE
Update alarm_control_panel.js

### PR DESCRIPTION
**Pull request by JAYMAN-ATX**
* reversed temporary workaround from https://github.com/home-assistant/homebridge-homeassistant/commit/01059c1e93ddb5ffbea3acee6dab2ff2753975e8
* fixed string to reflect correct state

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @JAYMAN-ATX, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;homebridge-homeassistant#262).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by schmittx** [comment]
Looks OK to me, can you update the README also?

**Comment by JAYMAN-ATX** [comment]
Sorry, I couldn't figure out how to add another file to this pull request, so I created another one.

**Comment by schmittx** [comment]
Looks good! Thanks!

**Comment by GraysonAdams** [comment]
I would like to point out that this issue does not appear to be resolved.

Pressing "Arm night" on the latest version for a manual alarm control panel component actually "Arms home" and makes HomeKit malfunction, as it is expecting the "Armed night" response and does not get it, so it just says... Pending......

**Comment by JAYMAN-ATX** [comment]
That patch is not yet included in the latest distribution package.  You have to modify the source file (accessories/alarm_control_panel.js) manually on your local server and restart homebridge to resolve the issue.

**Pull request merged**
