### PR TITLE
Battery tracking, air quality sensors, automations, default visibility, etc.

### LINKED ISSUE #161: add AirQuality

### LINKED ISSUE #169: Is there a way to invert the functionality of homebridge_hidden: true?
Is it possible for all "accessories" to be ignored unless something like homebridge_visible: true (or similar) is used under customise?

When you have MANY accessories this would be FAR easier to manage than homebridge_hidden: true.

Regards,
Michal

### LINKED ISSUE #191: alarm control panel with code
Cannot set the alarm if a code is required. it works just fine without code.
Need to find a way to set this in the config.

### LINKED ISSUE #195: Harmony Remote Switch state not being fetched
I notice that harmony remote activity "switch" states are not fetched when lights are updated.
Is this by design?  Or can the state be updated along with lights?
Home app frequently shows remotes as "off" while home-assistant correctly shows them as "on".
Thanks for the great plugin!

### PR DESCRIPTION
**Pull request by schmittx**
A handful of new features added!

Please use/test and give feedback where needed. I've done my best to test all of these using iOS Home app, but I can't duplicate every environment.

- Battery tracking for binary sensors, device trackers, locks, and sensors (see README for usage)
- Support for air quality sensors [Fixes #161]
- Ability to set default behavior for how devices are passed from Home Assistant (see README for usage) [Fixes #169 and #179 ]
- Support for automations (on/off)
- Fix remote states not being fetched [Fixes #195]
- Support for alarm control panels and codes (Fixes #191]
- Cleanup of the existing sensor component (temporary, until a more permanent/automated process can be put in place)

I also began the process of cleaning up and unifying a lot of the code. It's still a work in progress...

### CODE REVIEW

**Comment by schmittx** [comment]
@robbiet480 Whew, lots of Hound fixes. Sorry for the multiple commits, I'm still new to programming and not totally familiar with syntaxes and how to check my code beforehand. Anyway, it should be all good to go now and a good point to cut a new version.

**Comment by rbhr** [comment]
@schmittx we appreciate the efforts!

**Comment by maddox** [comment]
@schmittx There's a lot of great stuff in here, thanks!

Could you break this pull request up though? The mix of multiple new features, bug fixes, and refactors is a bit much for a single pull request. Besides making it easier to review, making individual pull requests makes it easier to merge each of your changes independently rather than all or nothing.

It's also helpful for the history of projects to have pull requests scoped and focused. It's easier to go back to see when/where something changed.

Try submitting a few pull requests for just the bug fixes first, than the feature additions, and then the refactors. Thanks!

**Comment by schmittx** [comment]
@maddox No problem! Like I said, I'm new to GitHub and appreciate the advice. I understand the concern for smaller-scope PRs though, I'll break this up and submit new PRs this week.

**Comment by maddox** [comment]
You rock!

**Pull request closed without merging**
