### PR TITLE
Add climate support for generic_thermostat

### PR DESCRIPTION
**Pull request by Minims**
Add support for generic_thermostat.

It's an alpha version but it's working on my side for my personal usage. 

 - physical thermostat not tested.
 - a/c mode not tested.
 - It's seems it fails if min_temp is defined under 10°C. HomeHit allow from 10° to 38°.
 - I can't find away mode in hass for the generic_thermostat, but it would be great to add if it exists.
 - Set Mode has no action on  Generic Thermostat, but I think the code is OK.

### CODE REVIEW

**Comment by Minims** [comment]
Maybe we can use the ClimateFactory to build Thermostat for all available climate devices and use `homebridge_climate_type: generic` in hass to define the type. I mean like cover.js for example.

**Comment by ssolmaz** [comment]
Hi @Minims ,
Thank you so much for your work.
You finished the work in a very short time. congratulations.
I have a home assistant server and have a working homebridge plugin.
I also have a generic thermostat.
How do I try it? Is plugin update enough?

**Comment by Minims** [comment]
Hi,
You need the last version of homebridge-homeassistant, because i saw many changes during the last days. (but it's not enough)

Update : 
`npm update -g homebridge-homeassistant`

Then backup index.js :
```
cd /usr/local/lib/node_modules/homebridge-homeassistant/
cp index.js index.js.bak
```
Download index.js & accessories/climate.js on my branch, and put them in : 
[index.js](https://raw.githubusercontent.com/Minims/homebridge-homeassistant/feature/climate_generic_thermostat/index.js)
[climate.js](https://raw.githubusercontent.com/Minims/homebridge-homeassistant/feature/climate_generic_thermostat/accessories/climate.js)
```
/usr/local/lib/node_modules/homebridge-homeassistant/index.js
/usr/local/lib/node_modules/homebridge-homeassistant/accessories/climate.js
```

In your homebridge config add climate : 
`...  "supported_types": ["climate", "binary_sensor", ...],`

Then restart homebrige. I hope it's clear enough .

**Comment by ssolmaz** [comment]
@Minims thank you for very descriptive information.
I will try as soon as possible.

**Comment by tobre6** [comment]
@Minims I tested your PR. I have 5 generic climate components. Overall it works good. Couple of issues:
1. I think it is important to have: homebridge_climate_type parameter. With this you can perhaps hide the Mode in the Home app UI, because for generic thermostat it is not neccessary.
2. When updating climate temp value in HASS, it is not getting updated right away in home app. I think it should be able to do it in onEvent callback.
3. Please update README as well with the new type


Otherwise good work! It was on my todo list, but now you should nail it! :)

**Comment by robbiet480** [comment]
Instead of going through the complicated procedure to install this that @Minims came up with, just run this command:

`npm install -g Minims/homebridge-homeassistant#feature/climate_generic_thermostat`

That will install his climate branch. Run that command again to update it as needed.

**Comment by Minims** [comment]
@robbiet480 thx for the easiest way :)

**Comment by Minims** [comment]
@tobre6 I've pushed some changes :

1. `homebridge_climate_type : generic`  is available. I've prepare the `else` for additional functions of phisical thermostat. It seems I can't hide the 'Mode' because `currentHeatingCoolingState` is defined as required in homebridge
2. Fix : Updating climate temp value in HASS is now working. (onEvent callback updated)
3. README updated, I've add device_tracker as supported device too.

**Comment by tobre6** [comment]
@Minims It fails when initializing
`/usr/local/lib/node_modules/homebridge-homeassistant/accessories/climate.js:182
    this.currentRelativeHumidity = Characteristic.CurrentRelativeHumidity;
    ^

ReferenceError: this is not defined
    at HomeAssistantClimatePhysical (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/climate.js:182:5)
    at HomeAssistantClimateFactory (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/climate.js:205:16)
    at /usr/local/lib/node_modules/homebridge-homeassistant/index.js:180:23
    at Request._callback (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:93:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
`

**Comment by Minims** [comment]
@tobre6 I've made a quick Fix, can you try again ?

**Comment by tobre6** [comment]
@Minims Good work! Looks nice! :)

**Comment by robbiet480** [comment]
What do we all think, is this good to merge?

**Comment by tobre6** [comment]
It works good in my opinion.

**Comment by ssolmaz** [comment]
congratulations.
I tested it many times. It works very well.
@Minims Thank you so much for this work

I did not try the mode section.
Which lines of the home assistant for this section should I add?
It would be nice to use off mode.

**Comment by Minims** [comment]
@ssolmaz I've not found a way to put a "Generic Thermostat"in 'OFF' state in hass. 
I discover hass few week ago, so i still don't know all the possibilities. If you have the API call to make such a thing i can check to add this feature in homebridge.

**Comment by ssolmaz** [comment]
@Minims I'm more inexperienced than you.
I made my first thermostat with a switch and a dht22.
I think it will only be useful. It will not be a problem for me to stay open all the time.
I saw a setting related to mode selection on the community home assistant.
But now i can't find it. I will take care of it again.
Thank you.

**Comment by robbiet480** [comment]
@Minims Okay, should we merge this?

**Comment by robbiet480** [comment]
So the problem i'm having now is we need to get this PR and #104 merged...

**Comment by Minims** [comment]
It's working on my side, i'm still using it without problem.  But as you said there is still your add_climate branch. I can make on new try with add_climate if you want.

**Comment by Minims** [comment]
I've just make a try with your branch add_climate, it seems working with generic_thermostat with the last version. 
Climate entity is loaded now, that was not the case when I start my own climate proposition. 
What about make it step by step, prod a first working version of your branch and update it later with new features  ?

**Comment by robbiet480** [comment]
@Minims I don't fully understand. Are you saying I should merge my `add_climate` branch since it appears to be working now? What new features need to be added?

**Comment by Minims** [comment]
Yes it's what I mean. sorry for my English.

I think ac/cooling mode will not work, but I haven't test.
A feature that can be add is a 'OFF' or 'Vacation' mode. For the moment, if you set mode to 'off' there is no action made.

**Comment by robbiet480** [comment]
Okay so should we close this and I will merge `add_climate` now then?

**Comment by Minims** [comment]
Yes :-)

**Pull request closed without merging**
