### PR TITLE
HA HB synchronization display mode change

### PR DESCRIPTION
**Pull request by roiff**
HA HB synchronization display mode change

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @roiff, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;homebridge-homeassistant#232).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Comment by roiff** [comment]
I am Chinese, I saw your article in China today, about the translation app, what can help you?

**Comment by robbiet480** [comment]
Hi @roiff that was for the iOS app, it's been fully translated now, thank you!

**Pull request merged**
