### PR TITLE
Create AirConditioner

### PR DESCRIPTION
**Pull request by roiff**
Create a fan control for the AirConditioner
```
homebridge_climate_type:  airconditioner
````
then close the fan at the same time will shut down the climate

This plug-in is very useful for air conditioning

+### Climate Support
 +If your device is air-conditioned then you have a thermostat and a fan, both working at the same time. In order
 +to do change this you may specify its type in the `customize` section of your
 +Home Assistant's `configuration.yaml`. Refer to the following example:
 +
 +```
 +customize:
 +  cover.living_room:
 +    homebridge_climate_type: airconditioner
 +```

### CODE REVIEW

**Comment by roiff** [comment]
@robbiet480 
Hello
This update is more useful for China or the Asian region because we are all using air conditioning equipment and fan control is a big issue that is rarely used in the United States and I hope you will be able to consider it as well as the official hap-nodejs Given the examples of air conditioners, Energizer guarantees logical justification
https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/AirConditioner_accessory.js

**Comment by schmittx** [comment]
I understand the purpose of this PR but I don't agree with the execution method. This needlessly duplicates a lot of the code that currently exists within `climate.js`.

I think a better method would be to allow the creation of an additional service (Fan or Fan v2) within the `climate.js` (currently just Thermostat and Accessory Information). This will create two entities within HomeKit, one for the Thermostat service and one for the Fan service.

I've created a rough draft of this concept for Nest Thermostats, reference [this](https://github.com/schmittx/homebridge-homeassistant/blob/prototype/accessories/custom/nest_thermostat.js).

Please update this existing PR or close and open a new one.

**Comment by roiff** [comment]
My original plan is such, can better refer to historical records, the original is a climate of fan design, because nobody wants, I again refer to hap nodejs, found him a separate independent from the air conditioner, after considering I feel is good, because of the climate in the HA fan attributes and inconsistencies, such as a speed_list, one is fan_mode, unless unified adjust HA logic, or add a lot of judgment in js statements, be inferior to separate out a logical, this is my thinking before and after

**Comment by roiff** [comment]
@schmittx 
In fact, air conditioning features are as follows:
Air conditioning operation, fan operation
The air conditioner stops and the fan stops
Will not run alone, the linkage if assigned to a separate independent annex, then the fan annex still need a large number of judgments
Another point, because the operation of air conditioning, almost no ability to adjust humidity, he will only make the humidity lower, which is also the operating mechanism of air conditioning jue'ding
I am in Asia, I also have homekit manufacturers, such as haier and other vendors, I also refer to their functions.

**Comment by roiff** [comment]
My advice
Climate allows the fan switch to be set individually. In many cases, it can be controlled independently of the temperature. A fan accessory can be generated separately for the climate, while the air conditioner can be a single climate type. After all, the two devices are running, and the principle is very different Big
Please refer to the operation of air conditioning, I hope you can think about it again

**Comment by roiff** [comment]
Finally, I will be based on your code and architecture, I consider how to update, thank you for your comments

**Comment by 5chacha5** [comment]
Hey there,

can we use it with https://github.com/vpnmaster/homeassistant-custom-components ?

thanks a lot

**Comment by roiff** [comment]
@5chacha5 can use
The official has updated a similar mechanism, you just need to update the version, this code is out of date

**Comment by roiff** [comment]
@5chacha5 There is a problem: The official update cannot turn off the air conditioner while turning off the fan, or vice versa. If you like this operation, also try using a similar code

**Comment by robbiet480** [comment]
Thanks for your submission. Sadly, homebridge-homeassistant is now deprecated so this code can't be accepted. Please find more information in the [README.md](https://github.com/home-assistant/homebridge-homeassistant#rotating_light-deprecated-rotating_light)

**Pull request closed without merging**
