### PR TITLE
Improve rollershutter to use WindowCovering service

### LINKED ISSUE #33: Add positioning and improved rollershutter support
Since we now have position in HomeAssistant for z-wave rollershutters, is it possible to switch the blinds "GarageDoor" implementation to a [WindowCovering](https://github.com/KhaosT/HAP-NodeJS/blob/6b18907afbda9eeaeef27eabfe22c35d901db1da/lib/gen/HomeKitTypes.js#L2423)?

This would allow for positioning like: "close my shutter to 30%"

### PR DESCRIPTION
**Pull request by nunofgs**
This PR replaces the rollershutter "GarageDoor" service with a "WindowCovering" component. This allows me to tell Siri to:

* "Close the shutter"
* "Open the shutter"
* "Open the shutter to 30%"
* etc.

It works beautifully with my Z-wave Fibaro FGR222 rollershutter. I can provide video of me using the integration if you guys find it interesting 😄 

The only drawback to this PR is that the open/close buttons are no longer displayed on my iOS app. I'm using Insteon+ so I'm not sure if it's specific to this app but it **did** show the buttons with the previous rollershutter implementation.

Here's what it looks like on the Insteon+ app:
keq5tvo

_Note to reviewers_: I didn't implement the [PositionState](https://github.com/KhaosT/HAP-NodeJS/blob/6b18907afbda9eeaeef27eabfe22c35d901db1da/lib/gen/HomeKitTypes.js#L2429) characteristic because HA doesn't expose the [decreasing/increasing/stopped](https://github.com/KhaosT/HAP-NodeJS/blob/6b18907afbda9eeaeef27eabfe22c35d901db1da/lib/gen/HomeKitTypes.js#L1156-L1158) states but everything seems to work properly!

Closes #33.

### CODE REVIEW

**Comment by robbiet480** [comment]
@nunofgs If you add `getOpenState` and `setOpenState` back the buttons should re-appear. Mind doing that? Then this can be merged.

**Comment by robbiet480** [comment]
@nunofgs Actually, before doing that, can you update to iOS 10 and use the Home app to see what it shows now?

**Comment by nunofgs** [comment]
@robbiet480: I tried adding `getOpenState` and `setOpenState` back, but if [you'll notice](https://github.com/KhaosT/HAP-NodeJS/blob/6b18907afbda9eeaeef27eabfe22c35d901db1da/lib/gen/HomeKitTypes.js#L2427-L2438) on hap-nodejs, the `CurrentDoorState` and `TargetDoorState` characteristics don't exist in the _WindowCovering_ service.

I also tried to add the characteristic, like this:

```js
    this.rollershutterService
      .addCharacteristic(Characteristic.CurrentDoorState)
      .on('get', this.getOpenState.bind(this));

    this.rollershutterService
      .addCharacteristic(Characteristic.TargetDoorState)
      .on('get', this.getOpenState.bind(this))
      .on('set', this.setOpenState.bind(this));
```

But still no go. The open/close buttons don't show up on either Insteon+ or Apple's Home app.

The Home app in iOS 10 also doesn't display buttons and the state is permanently "opening..." or "closing..." (even when the shutter is physically stopped). Here's what it looks like:

xpp09wx

Also, here it is on Elgato Eve's app:

dgpc1co

So it looks like the Eve app does see the "door state" correctly, but it seems a bit out of place. Doesn't look like this is the solution yet.

**Comment by robbiet480** [comment]
@nunofgs Maybe setting `CurrentPosition` to 0/100 when open/closed?

**Comment by nunofgs** [comment]
@robbiet480 tried it, buttons still don't show up. I did get it to stop "spinning" by adding the getter for the [TargetPosition characteristic](https://github.com/home-assistant/homebridge-homeassistant/pull/34/files#diff-2a3cc0027c8dadabfa2129d10921a5eeR71).

**Comment by robbiet480** [comment]
@Marioheld @n8henrie Can you weigh in on this? You both have worked on roller shutter/cover and implemented accessories before too, maybe you can figure out the missing open/close buttons?

**Comment by n8henrie** [comment]
I'll look through to see if I have any ideas.

I'd strongly suggest *adding* this as a component instead of *replacing* Rollershutter (which should be updated to use `cover` -- AFAIK rollershutter is deprecated and will be dropped). HomeKit [prevents you from verbally triggering a device named e.g. "garage door"](https://github.com/home-assistant/homebridge-homeassistant/issues/5) unless it is [`HMServiceTypeGarageDoorOpener`](https://developer.apple.com/reference/homekit/hmservicetypegaragedooropener).

So if you replace the `GarageDoor` service in the accessory, you won't be able to tell Siri to "open the garage" or "open the garage door" -- she'll respond that she can't find any garage doors, even if you've implemented your device as a switch or a `WindowCovering` and named it "garage door."

For that reason, I think this should be an *additional* accessory, not a replacement.

BTW, is anyone working on updating rollershutter to `cover`? Should be pretty simple.

**Comment by Marioheld** [comment]
Not quite sure why there no buttons appear. I will try tomorrow with the HomeKit Simulater to simulate a window covering to see if this behavior is normal.

**Comment by Marioheld** [comment]
Tested around with virtual devices. Seems like it is normal that a window covering has no open close buttons, only a slider for the position. Added Screenshots where Test Rolladen is a window covering and Test Rolladen alt is a garage door. Also it seems that insteon+ can´t handle window coverings for now. 
img_0645
img_0644
img_0643
img_0642
img_0641
img_0640

**Comment by fastender** [comment]
I am glad for you that it worked with you. I have not found a solution yet.

I can operate the blinds in my VERA and HA.

In HA, FIBARO has also been published under

cover.rolladen_links
{ "Vera Device Id": 51, "Current_position": 0, "Current_power_mwh": 0, "Friendly_name": "Rolladen left", "Homebridge_cover_type": "rollershutter" }

or

cover.rolladen_rechts
{ "Vera Device Id": 47, "Current_position": 0, "Current_power_mwh": 0, "Friendly_name": "Shutters right", "Homebridge_cover_type": "rollershutter"

---

In my IOS HOME app, FIBARO does not appear at all. All other devices, such as socket or switch, however, appear. The configuration config.json in the Homebridge is also correct:
{ "bridge": { "name": "Hass", "pin": "XXXXXXXXXXXX", "username": "XXXXXXXXXXXX" },
"platforms": [ { "platform": "HomeAssistant", "name": "HomeAssistant", "host": "XXXXXXXXXXXX:8123", "password": "XXXXXXXXXXXX", "supported_types": ["fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "switch"] } ] }

What am I doing wrong???

**Comment by nunofgs** [comment]
@fastender looks like the recent change of "rollershutter" to "cover" in home-assistant broke this PR. I'll try to get this working again soon.

**Comment by nunofgs** [comment]
@fastender Done. Seems to work for me now. Can you give it a try? (don't forget to rename "rollershutter" to "cover" in your config.json)

**Comment by fastender** [comment]
i make now fresh install of HASSbian and install homebridge new. i will inform u in a few minutes.

**Comment by fastender** [comment]
Unfortunately, again misrepresentation. The shutters are still not displayed. Can it be because of the fact that I have over Component Vera integrated the shutters into the HA?

in config.json

i add

"platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://192.168.178.81:8123",
            "password": "raspberry",
            "supported_types": ["fan", "garage_door", "input_boolean", "light", "lock", "media_player", "cover", "scene", "switch"]
        }
     ],

**Comment by robbiet480** [comment]
Closed via #55.

**Pull request closed without merging**
