### PR TITLE
Allow (optional) manual specification of accessory information

### PR DESCRIPTION
**Pull request by schmittx**
Adds ability to manually specify accessory information for each entity (if not specified, Homebridge will set it automatically).

You can specify the information (manufacturer, model, and serial number) using the following in customize.

```
customize:
  cover.garage_door:
    homebridge_mfg: Chamberlain
    homebridge_model: CIGCWC
    homebridge_serial: <REDACTED>
```

img_0753_small

### CODE REVIEW

**Comment by schmittx** [comment]
Apologies for the messy commit history, I'm still getting the hang of GitHub. I think this should be good to go now though.

**Comment by robbiet480** [comment]
@schmittx If you can go ahead and fix the merge conflict I'll get this merged. Going to cut a new version now, as soon as you get this fixed I will cut another version for you.

**Comment by schmittx** [comment]
@robbiet480 sounds good, I'll get it cleaned up this weekend. I'll also be making some new PRs as well, I've got air quality (binary) sensors working, battery tracking, and some other things working.

**Comment by schmittx** [comment]
Should be good to go now!

**Comment by robbiet480** [comment]
@schmittx Did you have other PRs that you planned to open soon? If so, i'll merge this but wait to cut a release so you can get your other PRs in.

**Comment by schmittx** [comment]
Yep!, give me an hour or two at max and I'll submit the rest of my PRs.

**Comment by robbiet480** [comment]
@schmittx I can just merge and not cut a release yet.

**Pull request merged**
